import type { TourDefinition, TourStep } from './types';

/** Desktop sidebar tour. */
export const desktopSidebarSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '',
    title: 'Welcome',
    body: "Welcome to Clippster. We'll walk through the main sidebar so you know where to download, clip, edit, and publish.",
  },
  {
    id: 'creators',
    target: 'nav-creators',
    title: 'My Creators',
    body: "Manage streamer and branding profiles for your clipping campaigns. Track who's live, auto-record streams, and configure intro/outro/watermark per creator.",
    group: 'Browse',
    placement: 'right',
    route: '/creators',
  },
  {
    id: 'live-clip',
    target: 'nav-live-clip',
    title: 'Live Streams',
    body: 'Paste a stream link or Mint ID to track a live channel. Watch, record, and run AI clip detection in real time — no profile setup required.',
    group: 'Browse',
    placement: 'right',
    route: '/live-clip',
    visible: (ctx) => ctx.isLiveClipEnabled !== false,
  },
  {
    id: 'vods',
    target: 'nav-vods',
    title: 'Download Video',
    body: 'Search and download VODs from YouTube, Twitch, Kick, Rumble, and more. Downloaded videos become projects in your Video library.',
    group: 'Browse',
    placement: 'right',
    route: '/vods',
  },
  {
    id: 'download-audio',
    target: 'nav-download-audio',
    title: 'Download Audio',
    body: 'Extract MP3 audio from YouTube URLs. Useful for podcasts, music, or audio-only content.',
    group: 'Browse',
    placement: 'right',
    route: '/download-audio',
  },
  {
    id: 'messages',
    target: 'nav-messages',
    title: 'Messages',
    body: 'Direct messages and group chats with team members and collaborators. A pinned Clippster Customer Support chat is always available here if you need help.',
    group: 'Browse',
    placement: 'right',
    route: '/messages',
  },
  {
    id: 'projects',
    target: 'nav-projects',
    title: 'Video',
    body: 'Your downloaded VOD projects. Organize sources, run AI clip detection, edit segments, and build clips from here.',
    group: 'Library',
    placement: 'right',
    route: '/projects',
  },
  {
    id: 'audio-library',
    target: 'nav-audio-library',
    title: 'Audio',
    body: 'Browse downloaded and uploaded audio files, create playlists, and manage your audio library.',
    group: 'Library',
    placement: 'right',
    route: '/audio-library',
  },
  {
    id: 'image-library',
    target: 'nav-image-library',
    title: 'Image',
    body: 'Local image assets — thumbnails, covers, AI-generated images, and editor exports. Filter by type and open in the Image Editor.',
    group: 'Library',
    placement: 'right',
    route: '/image-library',
  },
  {
    id: 'clips',
    target: 'nav-clips',
    title: 'Built Clips',
    body: 'Finished rendered clips (exports). Play, save, publish, or delete completed builds — not raw detections.',
    group: 'Library',
    placement: 'right',
    route: '/clips',
  },
  {
    id: 'video-editor',
    target: 'nav-video-editor',
    title: 'Video Editor',
    body: 'Launch multi-source timeline editor projects. Separate from your VOD library — for composing clips from multiple sources.',
    group: 'Design Studio',
    placement: 'right',
    route: '/video-editor',
  },
  {
    id: 'design-studio',
    target: 'nav-design-studio',
    title: 'Image Editor',
    body: 'Design thumbnails, banners, and social graphics on a canvas. Choose presets for YouTube, Shorts, Twitch, and more. (Beta)',
    group: 'Design Studio',
    placement: 'right',
    route: '/design-studio',
  },
  {
    id: 'studio-record',
    target: 'nav-studio-record',
    title: 'Recording',
    body: 'Record camera, screen, or both with branding overlays. Recordings save as editable projects you can clip from.',
    group: 'Studio',
    placement: 'right',
    route: '/studio/record',
  },
  {
    id: 'prompts',
    target: 'nav-prompts',
    title: 'Prompts',
    body: 'Custom AI prompt templates for clip detection. Use system defaults (Default Clip Detector, Gaming, etc.) or create your own for consistent detections.',
    group: 'Manage',
    placement: 'right',
    route: '/prompts',
    visible: (ctx) => !ctx.isRestricted,
  },
  {
    id: 'calendar',
    target: 'nav-calendar',
    title: 'Calendar',
    body: 'Plan and schedule social posts. Drag clips from the sidebar to schedule, track campaigns, and manage link submissions.',
    group: 'Manage',
    placement: 'right',
    route: '/calendar',
    visible: (ctx) => !ctx.isRestricted,
  },
  {
    id: 'profile',
    target: 'nav-profile-menu',
    title: 'Your Profile',
    body: 'Account settings, clipper profile, admin access, bug reports, and sign out.',
    placement: 'right',
  },
  {
    id: 'done',
    target: '',
    title: "You're all set",
    body: 'Restart this tour anytime from Account Settings.',
  },
];

export const desktopSidebarTour: TourDefinition = {
  id: 'desktop_sidebar',
  version: 'desktop-v1',
  steps: desktopSidebarSteps,
};

export const pageCreatorsSteps: TourStep[] = [
  {
    id: 'add-creator',
    target: 'tour-add-creator',
    title: 'Add Creator',
    body: 'Create a streamer profile with platform links (PumpFun, Kick, Twitch, YouTube, Rumble), intro/outro/watermark, and clip defaults. This is how Clippster knows who to track and how to brand their clips.',
    placement: 'bottom',
  },
  {
    id: 'streamer-vs-branding',
    target: 'tour-streamer-tab',
    title: 'Streamer vs Branding',
    body: 'Streamer Profiles are per-creator. Global Branding is shared branding you can reuse across creators.',
    placement: 'bottom',
  },
  {
    id: 'after-add',
    target: 'tour-creators-list',
    title: 'After you add one',
    body: 'On each creator card you can Watch, Rec (auto-record when live), and Auto (auto-detect clips for 60 min when live). Edit profile anytime from the menu.',
    placement: 'right',
  },
];

export const pageLiveClipSteps: TourStep[] = [
  {
    id: 'track',
    target: 'tour-live-search',
    title: 'Track a stream',
    body: 'Paste a stream URL or PumpFun Mint ID, then hit Track. Works with YouTube, Twitch, Kick, Rumble, X, and PumpFun.',
    placement: 'bottom',
  },
  {
    id: 'demo-streamer',
    target: 'tour-mock-streamer',
    title: 'Demo streamer',
    body: "Here's a sample tracked streamer so you can learn the controls. It disappears when this tour ends.",
    placement: 'right',
    injectMock: 'streamer',
  },
  {
    id: 'watch',
    target: 'tour-mock-watch',
    title: 'Watch',
    body: 'Opens a live watch window so you can see the stream while you record or detect clips.',
    placement: 'bottom',
    injectMock: 'streamer',
  },
  {
    id: 'rec',
    target: 'tour-mock-rec',
    title: 'Rec',
    body: 'Opens Record Settings, then starts recording this live stream into your library.',
    placement: 'bottom',
    injectMock: 'streamer',
  },
  {
    id: 'auto',
    target: 'tour-mock-auto',
    title: 'Auto',
    body: 'Opens Real-Time Clip Detection. Pick a prompt and Enable Auto Detect — AI finds clips for ~60 minutes while live.',
    placement: 'bottom',
    injectMock: 'streamer',
  },
];

export const pageVodsSteps: TourStep[] = [
  {
    id: 'platforms',
    target: 'tour-vod-platforms',
    title: 'Supported platforms',
    body: 'Search channels on Kick, Twitch, and PumpFun. Platforms: PumpFun, Kick, Twitch, YouTube, Rumble, X.',
    placement: 'bottom',
  },
  {
    id: 'full-videos',
    target: 'tour-vod-platforms',
    title: 'Videos, not just streams',
    body: 'YouTube, X, and Rumble also let you download full videos — not only live streams. YouTube and Rumble show Live Streams / Videos tabs.',
    placement: 'bottom',
  },
  {
    id: 'direct-links',
    target: 'tour-vod-search',
    title: 'Direct links (YouTube & X)',
    body: 'On YouTube and X you can paste a direct link to any video/post. X is link-only (no channel search). Downloads land in your Video library.',
    placement: 'bottom',
  },
];

export const pageProjectsSteps: TourStep[] = [
  {
    id: 'sample',
    target: 'tour-mock-project',
    title: 'Sample project',
    body: "This demo project shows the actions you'll use on every downloaded VOD. It disappears when the tour ends.",
    placement: 'right',
    injectMock: 'project',
  },
  {
    id: 'detect',
    target: 'tour-mock-detect',
    title: 'Detect Clips',
    body: 'Run AI clip detection to find highlight moments. Then open the project to edit segments and build clips.',
    placement: 'bottom',
    injectMock: 'project',
  },
  {
    id: 'transcribe',
    target: 'tour-mock-transcribe',
    title: 'Transcribe',
    body: "Generate a transcript for captions and transcript-based editing. Not needed if you've already run Detect Clips — detection covers the clip-finding step.",
    placement: 'bottom',
    injectMock: 'project',
  },
  {
    id: 'pre-edit',
    target: 'tour-mock-preedit',
    title: 'Pre-Edit VOD',
    body: 'Apply framing/layout presets to the entire VOD before detection — useful for vertical/shorts layouts. Set it once here so every clip inherits the same framing instead of editing each clip individually.',
    placement: 'bottom',
    injectMock: 'project',
  },
];

export const pageVideoEditorSteps: TourStep[] = [
  {
    id: 'welcome',
    target: 'tour-editor-preview',
    title: 'Welcome to the editor',
    body: 'This is your timeline editor project. Preview sits in the center; tools on the left; properties on the right; timeline along the bottom.',
    placement: 'left',
  },
  {
    id: 'left-rail',
    target: 'tour-editor-left-rail',
    title: 'Tool panels',
    body: "The left bar works like other video editors — Media, Text, Effects, Transitions, Captions, Transcript, Branding, and more. Click a panel to open it; you don't need every tool on day one.",
    placement: 'right',
  },
  {
    id: 'media',
    target: 'tour-editor-media',
    title: 'Media & import',
    body: 'Start here: click + to Import Media from Upload, Built Clips, Projects, Audio, or Images.',
    placement: 'right',
  },
  {
    id: 'properties',
    target: 'tour-editor-properties',
    title: 'Properties',
    body: 'The right panel shows details for whatever you have selected — clip settings, text options, and more. Select something on the timeline or canvas to edit it here.',
    placement: 'left',
  },
  {
    id: 'timeline',
    target: 'tour-editor-timeline',
    title: 'Timeline & playback',
    body: 'The bottom area is your timeline: tracks, playhead, and playback controls (Play/Pause with Space, jump to start, Split). Drag media here or double-click to add at the playhead; scrub to move through time.',
    placement: 'top',
  },
  {
    id: 'export',
    target: 'tour-editor-export',
    title: 'Export',
    body: 'When you\'re ready, Export opens Export Configuration to render your edit.',
    placement: 'bottom',
  },
];

export const pageImageEditorSteps: TourStep[] = [
  {
    id: 'welcome',
    target: 'tour-image-canvas',
    title: 'Welcome to the Image Editor',
    body: 'Early beta — features and UI may change. Canvas in the center; tools on the left; layers and properties on the right.',
    placement: 'right',
  },
  {
    id: 'tools',
    target: 'tour-image-tool-rail',
    title: 'Tools',
    body: "The left toolbar works like other image editors (Photoshop, Figma, etc.) — Move, Type, Crop, brush tools, shapes, and more. Pick a tool; the options bar shows its settings. You don't need every tool individually.",
    placement: 'right',
  },
  {
    id: 'media',
    target: 'tour-image-media',
    title: 'Media',
    body: 'Place images via Media — Upload, URL, Paste, Clips, or Gallery.',
    placement: 'left',
  },
  {
    id: 'layers',
    target: 'tour-image-layers',
    title: 'Layers & Properties',
    body: 'Layers lists everything on the canvas. Properties edits the selected layer.',
    placement: 'left',
  },
  {
    id: 'export',
    target: 'tour-image-export',
    title: 'Export',
    body: 'Export Image saves your design when you\'re done. Canvas size / templates live under Settings or More if you need a different preset.',
    placement: 'bottom',
  },
];

export const landingOrgSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '',
    title: 'Welcome',
    body: "Welcome to your organization dashboard. Here's what each section does.",
  },
  {
    id: 'hub',
    target: 'nav-hub',
    title: 'Hub',
    body: 'Your org home. See member count, creator profiles, assets, credits, and unread messages — with shortcuts to every section.',
    group: 'Team',
    placement: 'right',
  },
  {
    id: 'members',
    target: 'nav-members',
    title: 'Members',
    body: 'Invite team members (seat-limited by plan), manage roles, set credit allocations, and handle pending invitations.',
    group: 'Team',
    placement: 'right',
  },
  {
    id: 'creators',
    target: 'nav-creators',
    title: 'Creators',
    body: 'Creator profile library — streamer and global branding profiles with platform links, intro/outro/watermark, and member assignments.',
    group: 'Team',
    placement: 'right',
  },
  {
    id: 'messages',
    target: 'nav-messages',
    title: 'Messages',
    body: 'In-org messaging: direct messages, group chats, and org announcements. Real-time via WebSocket.',
    group: 'Team',
    placement: 'right',
  },
  {
    id: 'clippers',
    target: 'nav-clippers',
    title: 'Clippers',
    body: 'Browse the clipper talent directory or view the leaderboard. Filter by skills, invite clippers to campaigns, or message them.',
    group: 'Content',
    placement: 'right',
  },
  {
    id: 'shared',
    target: 'nav-shared',
    title: 'Shared Clips',
    body: 'Clip distribution hub. Admins share clips with members; everyone can preview and download. Tracks views, downloads, and posts.',
    group: 'Content',
    placement: 'right',
  },
  {
    id: 'social',
    target: 'nav-social',
    title: 'Social Accounts',
    body: 'Connect Instagram, TikTok, YouTube Shorts, and X for org publishing. Assign which members can post through each account.',
    group: 'Content',
    placement: 'right',
  },
  {
    id: 'posts',
    target: 'nav-posts',
    title: 'Posts',
    body: 'Post analytics across the org — views, likes, comments, and reach for scheduled posts, external posts, and campaign submissions.',
    group: 'Content',
    placement: 'right',
  },
  {
    id: 'assets',
    target: 'nav-assets',
    title: 'Assets',
    body: 'Org media library: intros, outros, watermarks, audio, and images for clipping workflows. Upload and preview assets.',
    group: 'Management',
    placement: 'right',
  },
  {
    id: 'billing',
    target: 'nav-billing',
    title: 'Billing',
    body: 'Org credit pool, member allocations, payment history, and subscription management. Admins can buy credits and change plans.',
    group: 'Management',
    placement: 'right',
  },
  {
    id: 'settings',
    target: 'nav-settings',
    title: 'Settings',
    body: 'Org profile, logo, bio, contact links, AI toggles, default restrictions for members, and org deletion (owner only).',
    group: 'Management',
    placement: 'right',
  },
  {
    id: 'done',
    target: '',
    title: 'Done',
    body: "You're ready to manage your team. Restart the tour from Settings anytime.",
  },
];

export const landingOrgTour: TourDefinition = {
  id: 'landing_org',
  version: 'landing-v1',
  steps: landingOrgSteps,
};

export const pageTours: Record<string, TourDefinition> = {
  page_creators: { id: 'page_creators', version: 'desktop-v1', steps: pageCreatorsSteps },
  page_live_clip: { id: 'page_live_clip', version: 'desktop-v1', steps: pageLiveClipSteps },
  page_vods: { id: 'page_vods', version: 'desktop-v1', steps: pageVodsSteps },
  page_projects: { id: 'page_projects', version: 'desktop-v1', steps: pageProjectsSteps },
  page_video_editor: { id: 'page_video_editor', version: 'desktop-v1', steps: pageVideoEditorSteps },
  page_image_editor: { id: 'page_image_editor', version: 'desktop-v1', steps: pageImageEditorSteps },
};
