defmodule ClippsterServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :clippster_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_clippster_server_key",
    signing_salt: "Z4Zyyi5g",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", ClippsterServerWeb.ProgressSocket,
    websocket: true,
    longpoll: false

  socket "/messaging", ClippsterServerWeb.MessagingSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :clippster_server,
    gzip: not code_reloading?,
    only: ClippsterServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :clippster_server
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # CORS must be at the endpoint level so headers are set on ALL responses,
  # including errors from pipeline plugs (e.g. :accepts rejecting multipart uploads)
  plug CORSPlug,
    origin: &ClippsterServerWeb.Router.cors_origins/0,
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
    headers: ["Authorization", "Content-Type", "Accept", "Origin", "X-Requested-With"],
    max_age: 86400,
    credentials: true

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 200_000_000,  # 200MB max request size for large video uploads
    body_reader: {ClippsterServerWeb.StripeWebhookPlug, :read_body, []}  # Capture raw body for Stripe webhooks

  # Debug: Print configuration info
  plug Plug.Logger, log: :debug

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ClippsterServerWeb.Router
end
