import type {
	CaptionPresetId,
	CaptionHighlightStyle,
	CaptionElement,
} from "../types/timeline";

export type CaptionPresetCategory = "single-word" | "classic" | "creator" | "colorful" | "effects";

export interface CaptionPreset {
	id: CaptionPresetId;
	name: string;
	category: CaptionPresetCategory;
	description: string;
	highlightStyle: CaptionHighlightStyle;
	highlightColor: string;
	color: string;
	backgroundColor: string;
	fontSize: number;
	fontFamily: string;
	fontWeight: CaptionElement["fontWeight"];
	fontStyle: CaptionElement["fontStyle"];
	letterSpacing: number;
	lineHeight: number;
	stroke?: CaptionElement["stroke"];
	shadow?: CaptionElement["shadow"];
	glow?: CaptionElement["glow"];
	gradient?: CaptionElement["gradient"];
	maxWordsPerLine: number;
}

export const CAPTION_PRESETS: CaptionPreset[] = [
	// ═══════════════════════════════════════
	// SINGLE-WORD — one word at a time, big & bold (CapCut "1 word" category)
	// ═══════════════════════════════════════
	{
		id: "single-bold",
		name: "Bold",
		category: "single-word",
		description: "One word at a time, big white bold",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-yellow",
		name: "Yellow Pop",
		category: "single-word",
		description: "Single word, yellow highlight pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-red",
		name: "Red Impact",
		category: "single-word",
		description: "Single word, red with thick stroke",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-green",
		name: "Green Flash",
		category: "single-word",
		description: "Single word, green highlight",
		highlightStyle: "karaoke-scale",
		highlightColor: "#22C55E",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-cyan",
		name: "Cyan Burst",
		category: "single-word",
		description: "Single word, cyan/teal pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-pink",
		name: "Pink Punch",
		category: "single-word",
		description: "Single word, hot pink pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-orange",
		name: "Orange Fire",
		category: "single-word",
		description: "Single word, orange highlight",
		highlightStyle: "karaoke-scale",
		highlightColor: "#F97316",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-purple",
		name: "Purple Haze",
		category: "single-word",
		description: "Single word, purple pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#A855F7",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-boxed",
		name: "Boxed Word",
		category: "single-word",
		description: "Single word in a colored box",
		highlightStyle: "background",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.7)",
		fontSize: 56,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		maxWordsPerLine: 1,
	},
	{
		id: "single-glow",
		name: "Glow Word",
		category: "single-word",
		description: "Single word with neon glow",
		highlightStyle: "glow",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 60,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		glow: { color: "#22D3EE", intensity: 20 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-outline",
		name: "Outline Word",
		category: "single-word",
		description: "Single word, outline only",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "transparent",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#FFFFFF", width: 3 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-gradient",
		name: "Gradient Word",
		category: "single-word",
		description: "Single word with gradient fill",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		gradient: { enabled: true, colors: ["#F97316", "#EC4899"], angle: 135 },
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-shadow",
		name: "Shadow Word",
		category: "single-word",
		description: "Single word with heavy drop shadow",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 4, offsetY: 4, blur: 8 },
		maxWordsPerLine: 1,
	},

	// ═══════════════════════════════════════
	// CLASSIC — standard multi-word caption styles
	// ═══════════════════════════════════════
	{
		id: "default",
		name: "Default",
		category: "classic",
		description: "Clean white text with shadow",
		highlightStyle: "none",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 42,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		shadow: { color: "rgba(0,0,0,0.8)", offsetX: 2, offsetY: 2, blur: 4 },
		maxWordsPerLine: 4,
	},
	{
		id: "karaoke",
		name: "Karaoke",
		category: "classic",
		description: "Word-by-word color highlight",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 4,
	},
	{
		id: "karaoke-pop",
		name: "Karaoke Pop",
		category: "classic",
		description: "Word-by-word highlight with scale pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#F97316",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.4,
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 3,
	},
	{
		id: "bold-outline",
		name: "Bold Outline",
		category: "classic",
		description: "Thick outlined text",
		highlightStyle: "karaoke",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 52,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 3,
	},
	{
		id: "boxed",
		name: "Boxed",
		category: "classic",
		description: "Words in colored boxes",
		highlightStyle: "background",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.6)",
		fontSize: 40,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.5,
		maxWordsPerLine: 4,
	},
	{
		id: "typewriter",
		name: "Typewriter",
		category: "classic",
		description: "Monospace with underline highlight",
		highlightStyle: "underline",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 36,
		fontFamily: "Roboto Condensed",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.4,
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 1, offsetY: 1, blur: 3 },
		maxWordsPerLine: 5,
	},
	{
		id: "minimal",
		name: "Minimal",
		category: "classic",
		description: "Simple clean subtitles",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.5)",
		fontSize: 32,
		fontFamily: "Inter",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		maxWordsPerLine: 6,
	},

	// ═══════════════════════════════════════
	// CREATOR — named after popular creator styles
	// ═══════════════════════════════════════
	{
		id: "hormozi",
		name: "Hormozi",
		category: "creator",
		description: "Bold yellow highlight, 2 words per line",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 56,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 2,
	},
	{
		id: "ali-abdaal",
		name: "Ali Abdaal",
		category: "creator",
		description: "Clean, soft highlight with background",
		highlightStyle: "background",
		highlightColor: "#3B82F6",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.4)",
		fontSize: 38,
		fontFamily: "Inter",
		fontWeight: "600",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 5,
	},
	{
		id: "mr-beast",
		name: "MrBeast",
		category: "creator",
		description: "Huge bold text, red/yellow pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EF4444",
		color: "#FACC15",
		backgroundColor: "transparent",
		fontSize: 60,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 6 },
		maxWordsPerLine: 2,
	},
	{
		id: "elegant",
		name: "Elegant",
		category: "creator",
		description: "Refined serif-style captions",
		highlightStyle: "underline",
		highlightColor: "#D4AF37",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 40,
		fontFamily: "Georgia",
		fontWeight: "normal",
		fontStyle: "italic",
		letterSpacing: 1,
		lineHeight: 1.5,
		shadow: { color: "rgba(0,0,0,0.6)", offsetX: 1, offsetY: 2, blur: 4 },
		maxWordsPerLine: 5,
	},
	{
		id: "comic",
		name: "Comic",
		category: "creator",
		description: "Fun comic-book style",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 50,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#1E3A5F", width: 5 },
		shadow: { color: "#1E3A5F", offsetX: 3, offsetY: 3, blur: 0 },
		maxWordsPerLine: 3,
	},
	{
		id: "retro",
		name: "Retro",
		category: "creator",
		description: "Vintage retro vibe",
		highlightStyle: "karaoke",
		highlightColor: "#F97316",
		color: "#FDE68A",
		backgroundColor: "transparent",
		fontSize: 44,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 3,
		lineHeight: 1.3,
		stroke: { color: "#7C2D12", width: 4 },
		shadow: { color: "#7C2D12", offsetX: 3, offsetY: 3, blur: 0 },
		maxWordsPerLine: 3,
	},

	// ═══════════════════════════════════════
	// COLORFUL — gradient and color-heavy styles
	// ═══════════════════════════════════════
	{
		id: "gradient-pop",
		name: "Gradient Pop",
		category: "colorful",
		description: "Gradient text with pop highlight",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#F97316", "#EC4899"], angle: 135 },
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "gradient-blue",
		name: "Ocean Blue",
		category: "colorful",
		description: "Blue-to-cyan gradient",
		highlightStyle: "karaoke-scale",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#3B82F6", "#22D3EE"], angle: 90 },
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "gradient-sunset",
		name: "Sunset",
		category: "colorful",
		description: "Warm sunset gradient",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#EF4444", "#FACC15"], angle: 90 },
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "gradient-neon",
		name: "Neon Gradient",
		category: "colorful",
		description: "Electric neon gradient",
		highlightStyle: "karaoke-scale",
		highlightColor: "#A855F7",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#06B6D4", "#A855F7"], angle: 135 },
		stroke: { color: "#000000", width: 3 },
		glow: { color: "#A855F7", intensity: 10 },
		maxWordsPerLine: 3,
	},
	{
		id: "fire",
		name: "Fire",
		category: "colorful",
		description: "Red-orange fire colors",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#F97316",
		backgroundColor: "transparent",
		fontSize: 52,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#7C2D12", width: 4 },
		glow: { color: "#EF4444", intensity: 12 },
		maxWordsPerLine: 3,
	},
	{
		id: "ice",
		name: "Ice",
		category: "colorful",
		description: "Cool blue ice colors",
		highlightStyle: "karaoke",
		highlightColor: "#FFFFFF",
		color: "#93C5FD",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#1E3A5F", width: 3 },
		glow: { color: "#60A5FA", intensity: 12 },
		maxWordsPerLine: 4,
	},
	{
		id: "pastel",
		name: "Pastel",
		category: "colorful",
		description: "Soft pastel tones",
		highlightStyle: "karaoke",
		highlightColor: "#F9A8D4",
		color: "#E9D5FF",
		backgroundColor: "transparent",
		fontSize: 44,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		shadow: { color: "rgba(0,0,0,0.4)", offsetX: 2, offsetY: 2, blur: 6 },
		maxWordsPerLine: 4,
	},

	// ═══════════════════════════════════════
	// EFFECTS — stroke, shadow, glow focused
	// ═══════════════════════════════════════
	{
		id: "neon-glow",
		name: "Neon Glow",
		category: "effects",
		description: "Glowing neon text",
		highlightStyle: "glow",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 44,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		glow: { color: "#22D3EE", intensity: 15 },
		maxWordsPerLine: 4,
	},
	{
		id: "thick-stroke",
		name: "Thick Stroke",
		category: "effects",
		description: "Extra thick black outline",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 52,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 8 },
		maxWordsPerLine: 3,
	},
	{
		id: "drop-shadow",
		name: "Drop Shadow",
		category: "effects",
		description: "Heavy drop shadow effect",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		shadow: { color: "rgba(0,0,0,0.95)", offsetX: 4, offsetY: 4, blur: 0 },
		maxWordsPerLine: 3,
	},
	{
		id: "highlight-box",
		name: "Highlight Box",
		category: "effects",
		description: "Active word gets a colored box",
		highlightStyle: "background",
		highlightColor: "#3B82F6",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 44,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.5,
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 4,
	},
	{
		id: "underline-pop",
		name: "Underline Pop",
		category: "effects",
		description: "Underline highlight with pop",
		highlightStyle: "underline",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 46,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "glitch",
		name: "Glitch",
		category: "effects",
		description: "Glitchy offset shadow effect",
		highlightStyle: "karaoke",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 2 },
		shadow: { color: "#EF4444", offsetX: 3, offsetY: -2, blur: 0 },
		maxWordsPerLine: 3,
	},
];

export const DEFAULT_CAPTION_ELEMENT: Omit<CaptionElement, "id" | "lines" | "startTime" | "duration" | "trimStart" | "trimEnd" | "name" | "type"> = {
	presetId: "karaoke",
	highlightStyle: "karaoke",
	highlightColor: "#FACC15",
	fontSize: 48,
	fontFamily: "Montserrat",
	color: "#FFFFFF",
	backgroundColor: "transparent",
	textAlign: "center",
	fontWeight: "bold",
	fontStyle: "normal",
	letterSpacing: 0,
	lineHeight: 1.3,
	textCase: "none",
	stroke: { color: "#000000", width: 3 },
	transform: { scale: 1, position: { x: 0, y: 200 }, rotate: 0 },
	opacity: 1,
	maxWordsPerLine: 4,
};

export function getPresetById(id: CaptionPresetId): CaptionPreset {
	return CAPTION_PRESETS.find((p) => p.id === id) ?? CAPTION_PRESETS[0];
}
