import type {
	CaptionPresetId,
	CaptionHighlightStyle,
	CaptionElement,
} from "../types/timeline";

export type CaptionPresetCategory = "single-word" | "classic" | "creator" | "colorful" | "effects";

export interface CaptionPreset {
	id: CaptionPresetId;
	name: string;
	category: CaptionPresetCategory;
	description: string;
	highlightStyle: CaptionHighlightStyle;
	highlightColor: string;
	color: string;
	backgroundColor: string;
	fontSize: number;
	fontFamily: string;
	fontWeight: CaptionElement["fontWeight"];
	fontStyle: CaptionElement["fontStyle"];
	letterSpacing: number;
	lineHeight: number;
	stroke?: CaptionElement["stroke"];
	shadow?: CaptionElement["shadow"];
	glow?: CaptionElement["glow"];
	gradient?: CaptionElement["gradient"];
	maxWordsPerLine: number;
}

export const CAPTION_PRESETS: CaptionPreset[] = [
	// ═══════════════════════════════════════
	// SINGLE-WORD — one word at a time, big & bold (CapCut "1 word" category)
	// ═══════════════════════════════════════
	{
		id: "single-bold",
		name: "Bold",
		category: "single-word",
		description: "One word at a time, big white bold",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Bebas Neue",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 3,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-yellow",
		name: "Yellow Pop",
		category: "single-word",
		description: "Single word, yellow highlight pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-boxed",
		name: "Boxed Word",
		category: "single-word",
		description: "Single word in a colored box",
		highlightStyle: "background",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.7)",
		fontSize: 56,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		maxWordsPerLine: 1,
	},
	{
		id: "single-glow",
		name: "Glow Word",
		category: "single-word",
		description: "Single word with neon glow",
		highlightStyle: "glow",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 60,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		glow: { color: "#22D3EE", intensity: 20 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-outline",
		name: "Outline Word",
		category: "single-word",
		description: "Single word, outline only",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "transparent",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#FFFFFF", width: 3 },
		maxWordsPerLine: 1,
	},
	{
		id: "single-gradient",
		name: "Gradient Word",
		category: "single-word",
		description: "Single word with gradient fill",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 64,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.2,
		gradient: { enabled: true, colors: ["#F97316", "#EC4899"], angle: 135 },
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 1,
	},

	// ═══════════════════════════════════════
	// CLASSIC — standard multi-word caption styles
	// ═══════════════════════════════════════
	{
		id: "default",
		name: "Default",
		category: "classic",
		description: "Clean white text with shadow",
		highlightStyle: "none",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 42,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		shadow: { color: "rgba(0,0,0,0.8)", offsetX: 2, offsetY: 2, blur: 4 },
		maxWordsPerLine: 4,
	},
	{
		id: "karaoke",
		name: "Karaoke",
		category: "classic",
		description: "Word-by-word color highlight",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 4,
	},
	{
		id: "karaoke-pop",
		name: "Karaoke Pop",
		category: "classic",
		description: "Word-by-word highlight with scale pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#F97316",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.4,
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 3,
	},
	{
		id: "boxed",
		name: "Boxed",
		category: "classic",
		description: "Words in colored boxes",
		highlightStyle: "background",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.6)",
		fontSize: 40,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.5,
		maxWordsPerLine: 4,
	},

	// ═══════════════════════════════════════
	// CREATOR — named after popular creator styles
	// ═══════════════════════════════════════
	{
		id: "hormozi",
		name: "Hormozi",
		category: "creator",
		description: "Bold yellow highlight, 2 words per line",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 56,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 5 },
		maxWordsPerLine: 2,
	},
	{
		id: "mr-beast",
		name: "MrBeast",
		category: "creator",
		description: "Huge bold text, red/yellow pop",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EF4444",
		color: "#FACC15",
		backgroundColor: "transparent",
		fontSize: 60,
		fontFamily: "Bebas Neue",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 3,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 6 },
		maxWordsPerLine: 2,
	},
	{
		id: "ali-abdaal",
		name: "Ali Abdaal",
		category: "creator",
		description: "Clean minimal with subtle blue highlight",
		highlightStyle: "karaoke",
		highlightColor: "#60A5FA",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.5)",
		fontSize: 34,
		fontFamily: "Inter",
		fontWeight: "500",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 5,
	},
	{
		id: "mkbhd",
		name: "MKBHD",
		category: "creator",
		description: "Sharp red accent, clean sans-serif",
		highlightStyle: "karaoke",
		highlightColor: "#EF4444",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 38,
		fontFamily: "Roboto",
		fontWeight: "700",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 2, offsetY: 2, blur: 6 },
		maxWordsPerLine: 4,
	},
	{
		id: "gary-vee",
		name: "Gary Vee",
		category: "creator",
		description: "Big bold motivational, 1-2 words per line",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 62,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 6 },
		shadow: { color: "rgba(0,0,0,0.8)", offsetX: 3, offsetY: 3, blur: 0 },
		maxWordsPerLine: 2,
	},

	// ═══════════════════════════════════════
	// COLORFUL — gradient and color-heavy styles
	// ═══════════════════════════════════════
	{
		id: "gradient-pop",
		name: "Gradient Pop",
		category: "colorful",
		description: "Gradient text with pop highlight",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#F97316", "#EC4899"], angle: 135 },
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "gradient-neon",
		name: "Neon Gradient",
		category: "colorful",
		description: "Electric neon gradient",
		highlightStyle: "karaoke-scale",
		highlightColor: "#A855F7",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#06B6D4", "#A855F7"], angle: 135 },
		stroke: { color: "#000000", width: 3 },
		glow: { color: "#A855F7", intensity: 10 },
		maxWordsPerLine: 3,
	},

	// ═══════════════════════════════════════
	// EFFECTS — stroke, shadow, glow focused
	// ═══════════════════════════════════════
	{
		id: "neon-glow",
		name: "Neon Glow",
		category: "effects",
		description: "Glowing neon text",
		highlightStyle: "glow",
		highlightColor: "#22D3EE",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 44,
		fontFamily: "Montserrat",
		fontWeight: "bold",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		glow: { color: "#22D3EE", intensity: 15 },
		maxWordsPerLine: 4,
	},

	// ═══════════════════════════════════════
	// TIKTOK PACK — trending TikTok styles 2026
	// ═══════════════════════════════════════
	{
		id: "tiktok-bold",
		name: "TikTok Bold",
		category: "colorful",
		description: "Bold high-contrast for TikTok",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.8)",
		fontSize: 52,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 3,
	},
	{
		id: "tiktok-gen-z",
		name: "Gen Z Pop",
		category: "colorful",
		description: "Rose-violet trendy style",
		highlightStyle: "karaoke-scale",
		highlightColor: "#EC4899",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 50,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#EC4899", "#A855F7"], angle: 135 },
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 2,
	},
	{
		id: "tiktok-mobile",
		name: "Mobile First",
		category: "classic",
		description: "Optimized for mobile viewing",
		highlightStyle: "background",
		highlightColor: "#FACC15",
		color: "#000000",
		backgroundColor: "rgba(250,204,21,0.9)",
		fontSize: 46,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.5,
		maxWordsPerLine: 3,
	},

	// ═══════════════════════════════════════
	// YOUTUBE PACK — professional YouTube styles
	// ═══════════════════════════════════════
	{
		id: "youtube-tutorial",
		name: "Tutorial Clean",
		category: "classic",
		description: "Clean readable for tutorials",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.75)",
		fontSize: 36,
		fontFamily: "Roboto",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 6,
	},
	{
		id: "youtube-pro",
		name: "YouTube Pro",
		category: "classic",
		description: "Professional YouTube style",
		highlightStyle: "karaoke",
		highlightColor: "#FF0000",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 40,
		fontFamily: "Roboto",
		fontWeight: "600",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 2, offsetY: 2, blur: 4 },
		maxWordsPerLine: 5,
	},
	{
		id: "youtube-vlog",
		name: "Vlog Style",
		category: "creator",
		description: "Casual vlog captions",
		highlightStyle: "karaoke",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 38,
		fontFamily: "Inter",
		fontWeight: "600",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		shadow: { color: "rgba(0,0,0,0.8)", offsetX: 2, offsetY: 2, blur: 6 },
		maxWordsPerLine: 5,
	},

	// ═══════════════════════════════════════
	// INSTAGRAM PACK — aesthetic Instagram styles
	// ═══════════════════════════════════════
	{
		id: "instagram-aesthetic",
		name: "Aesthetic",
		category: "creator",
		description: "Soft aesthetic for lifestyle",
		highlightStyle: "underline",
		highlightColor: "#F9A8D4",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 40,
		fontFamily: "Inter",
		fontWeight: "500",
		fontStyle: "italic",
		letterSpacing: 1,
		lineHeight: 1.5,
		shadow: { color: "rgba(0,0,0,0.6)", offsetX: 1, offsetY: 2, blur: 6 },
		maxWordsPerLine: 5,
	},
	{
		id: "instagram-story",
		name: "Story Style",
		category: "colorful",
		description: "Perfect for Instagram Stories",
		highlightStyle: "karaoke-scale",
		highlightColor: "#E91E63",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "800",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#E91E63", "#9C27B0"], angle: 90 },
		stroke: { color: "#000000", width: 3 },
		maxWordsPerLine: 3,
	},
	{
		id: "instagram-reel",
		name: "Reel Pop",
		category: "colorful",
		description: "Energetic for Reels",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FF6B6B",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 50,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 5 },
		glow: { color: "#FF6B6B", intensity: 12 },
		maxWordsPerLine: 2,
	},

	// ═══════════════════════════════════════
	// PODCAST PACK — minimal readable styles
	// ═══════════════════════════════════════
	{
		id: "podcast-minimal",
		name: "Podcast Minimal",
		category: "classic",
		description: "Clean minimal for podcasts",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.6)",
		fontSize: 34,
		fontFamily: "Inter",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 7,
	},
	{
		id: "podcast-highlight",
		name: "Podcast Highlight",
		category: "classic",
		description: "Subtle word highlight",
		highlightStyle: "karaoke",
		highlightColor: "#60A5FA",
		color: "#E5E7EB",
		backgroundColor: "rgba(0,0,0,0.7)",
		fontSize: 36,
		fontFamily: "Inter",
		fontWeight: "500",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 6,
	},
	{
		id: "podcast-pro",
		name: "Podcast Pro",
		category: "classic",
		description: "Professional podcast style",
		highlightStyle: "underline",
		highlightColor: "#3B82F6",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.65)",
		fontSize: 38,
		fontFamily: "Roboto",
		fontWeight: "500",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 6,
	},

	// ═══════════════════════════════════════
	// GAMING PACK — energetic gaming styles
	// ═══════════════════════════════════════
	{
		id: "gaming-neon",
		name: "Gaming Neon",
		category: "effects",
		description: "Electric neon for gaming",
		highlightStyle: "glow",
		highlightColor: "#00FF00",
		color: "#00FF00",
		backgroundColor: "transparent",
		fontSize: 46,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.3,
		glow: { color: "#00FF00", intensity: 20 },
		stroke: { color: "#000000", width: 2 },
		maxWordsPerLine: 3,
	},
	{
		id: "gaming-cyber",
		name: "Cyberpunk",
		category: "effects",
		description: "Cyberpunk futuristic style",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FF00FF",
		color: "#00FFFF",
		backgroundColor: "transparent",
		fontSize: 48,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 3,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 3 },
		glow: { color: "#FF00FF", intensity: 15 },
		maxWordsPerLine: 3,
	},
	{
		id: "gaming-action",
		name: "Action",
		category: "effects",
		description: "High-energy action style",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FF0000",
		color: "#FACC15",
		backgroundColor: "transparent",
		fontSize: 54,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.2,
		stroke: { color: "#000000", width: 6 },
		shadow: { color: "#FF0000", offsetX: 3, offsetY: 3, blur: 0 },
		maxWordsPerLine: 2,
	},

	// ═══════════════════════════════════════
	// BUSINESS PACK — professional business styles
	// ═══════════════════════════════════════
	{
		id: "business-clean",
		name: "Business Clean",
		category: "classic",
		description: "Professional business style",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.8)",
		fontSize: 36,
		fontFamily: "Inter",
		fontWeight: "500",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 6,
	},
	{
		id: "business-accent",
		name: "Business Accent",
		category: "classic",
		description: "Professional with blue accent",
		highlightStyle: "karaoke",
		highlightColor: "#3B82F6",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.75)",
		fontSize: 38,
		fontFamily: "Inter",
		fontWeight: "600",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 5,
	},
	{
		id: "business-modern",
		name: "Modern Business",
		category: "classic",
		description: "Modern corporate style",
		highlightStyle: "underline",
		highlightColor: "#10B981",
		color: "#F3F4F6",
		backgroundColor: "rgba(17,24,39,0.85)",
		fontSize: 36,
		fontFamily: "Inter",
		fontWeight: "500",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 6,
	},

	// ═══════════════════════════════════════
	// MOTIVATIONAL PACK — inspirational styles
	// ═══════════════════════════════════════
	{
		id: "motivational-bold",
		name: "Motivational",
		category: "creator",
		description: "Bold motivational quotes",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FACC15",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 54,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 2,
		lineHeight: 1.3,
		stroke: { color: "#000000", width: 6 },
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 3, offsetY: 3, blur: 6 },
		maxWordsPerLine: 2,
	},
	{
		id: "motivational-gradient",
		name: "Inspire",
		category: "colorful",
		description: "Inspirational gradient",
		highlightStyle: "karaoke-scale",
		highlightColor: "#FBBF24",
		color: "#FFFFFF",
		backgroundColor: "transparent",
		fontSize: 50,
		fontFamily: "Montserrat",
		fontWeight: "900",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.3,
		gradient: { enabled: true, colors: ["#FBBF24", "#F59E0B"], angle: 90 },
		stroke: { color: "#000000", width: 4 },
		maxWordsPerLine: 2,
	},

	// ═══════════════════════════════════════
	// SUBTITLE — smaller, positioned lower, for documentary/tutorial
	// ═══════════════════════════════════════
	{
		id: "subtitle-documentary",
		name: "Documentary",
		category: "classic",
		description: "Subtle lower-positioned subtitles for docs",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#E5E7EB",
		backgroundColor: "rgba(0,0,0,0.5)",
		fontSize: 30,
		fontFamily: "Inter",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 8,
	},
	{
		id: "subtitle-tutorial",
		name: "Tutorial Sub",
		category: "classic",
		description: "Small clean subtitles for tutorials",
		highlightStyle: "karaoke",
		highlightColor: "#60A5FA",
		color: "#FFFFFF",
		backgroundColor: "rgba(0,0,0,0.6)",
		fontSize: 28,
		fontFamily: "Roboto",
		fontWeight: "normal",
		fontStyle: "normal",
		letterSpacing: 0,
		lineHeight: 1.4,
		maxWordsPerLine: 7,
	},
	{
		id: "subtitle-cinematic",
		name: "Cinematic Sub",
		category: "classic",
		description: "Elegant thin subtitles for cinematic content",
		highlightStyle: "none",
		highlightColor: "#FFFFFF",
		color: "#D4D4D8",
		backgroundColor: "transparent",
		fontSize: 32,
		fontFamily: "Inter",
		fontWeight: "300",
		fontStyle: "normal",
		letterSpacing: 1,
		lineHeight: 1.5,
		shadow: { color: "rgba(0,0,0,0.9)", offsetX: 1, offsetY: 1, blur: 4 },
		maxWordsPerLine: 8,
	},
];

export const DEFAULT_CAPTION_ELEMENT: Omit<CaptionElement, "id" | "lines" | "startTime" | "duration" | "trimStart" | "trimEnd" | "name" | "type"> = {
	presetId: "karaoke",
	highlightStyle: "karaoke",
	highlightColor: "#FACC15",
	fontSize: 48,
	fontFamily: "Montserrat",
	color: "#FFFFFF",
	backgroundColor: "transparent",
	textAlign: "center",
	fontWeight: "bold",
	fontStyle: "normal",
	letterSpacing: 0,
	lineHeight: 1.3,
	textCase: "none",
	stroke: { color: "#000000", width: 3 },
	transform: { scale: 1, position: { x: 0, y: 200 }, rotate: 0 },
	opacity: 1,
	maxWordsPerLine: 4,
};

export function getPresetById(id: CaptionPresetId): CaptionPreset {
	return CAPTION_PRESETS.find((p) => p.id === id) ?? CAPTION_PRESETS[0];
}
