import type { TextElement, TextBubbleStyle } from "../types/timeline";
import { TIMELINE_CONSTANTS } from "./timeline-constants";

export const DEFAULT_TEXT_ELEMENT: Omit<TextElement, "id"> = {
	type: "text",
	name: "Text",
	content: "Default Text",
	fontSize: 48,
	fontFamily: "Inter",
	color: "#ffffff",
	backgroundColor: "transparent",
	textAlign: "center",
	fontWeight: "normal",
	fontStyle: "normal",
	textDecoration: "none",
	letterSpacing: 0,
	lineHeight: 1.2,
	textCase: "none",
	bubbleStyle: "none",
	duration: TIMELINE_CONSTANTS.DEFAULT_ELEMENT_DURATION,
	startTime: 0,
	trimStart: 0,
	trimEnd: 0,
	transform: {
		scale: 1,
		position: {
			x: 0,
			y: 0,
		},
		rotate: 0,
	},
	opacity: 1,
};

export interface TextPreset {
	id: string;
	name: string;
	category: TextPresetCategory;
	thumbnail?: string;
	element: Partial<Omit<TextElement, "id" | "type" | "startTime" | "trimStart" | "trimEnd" | "duration">>;
}

export type TextPresetCategory =
	| "basic"
	| "titles"
	| "subtitles"
	| "social"
	| "gaming"
	| "neon"
	| "bubbles"
	| "handwritten";

export const TEXT_PRESETS: TextPreset[] = [
	// ═══ BASIC ═══
	{
		id: "basic-clean",
		name: "Clean",
		category: "basic",
		element: {
			content: "Clean Text",
			fontSize: 48,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "500",
		},
	},
	{
		id: "basic-bold",
		name: "Bold",
		category: "basic",
		element: {
			content: "Bold Text",
			fontSize: 56,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "800",
		},
	},
	{
		id: "basic-thin",
		name: "Thin",
		category: "basic",
		element: {
			content: "Thin & Light",
			fontSize: 52,
			fontFamily: "Inter",
			color: "#d4d4d8",
			fontWeight: "200",
			letterSpacing: 3,
		},
	},
	{
		id: "basic-outlined",
		name: "Outlined",
		category: "basic",
		element: {
			content: "OUTLINED",
			fontSize: 60,
			fontFamily: "Inter",
			color: "transparent",
			fontWeight: "800",
			textCase: "uppercase",
			stroke: { color: "#ffffff", width: 2 },
			letterSpacing: 4,
		},
	},

	// ═══ TITLES ═══
	{
		id: "title-impact",
		name: "Impact",
		category: "titles",
		element: {
			content: "IMPACT",
			fontSize: 84,
			fontFamily: "Impact",
			color: "#ffffff",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 4 },
			letterSpacing: 3,
		},
	},
	{
		id: "title-cinematic",
		name: "Cinematic",
		category: "titles",
		element: {
			content: "CINEMATIC",
			fontSize: 68,
			fontFamily: "Bebas Neue",
			color: "#ffffff",
			fontWeight: "normal",
			textCase: "uppercase",
			letterSpacing: 12,
			shadow: { color: "rgba(0,0,0,0.9)", offsetX: 0, offsetY: 4, blur: 12 },
		},
	},
	{
		id: "title-sunset-gradient",
		name: "Sunset",
		category: "titles",
		element: {
			content: "SUNSET",
			fontSize: 76,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "900",
			textCase: "uppercase",
			gradient: { enabled: true, colors: ["#f97316", "#ec4899"], angle: 135 },
			letterSpacing: 4,
		},
	},
	{
		id: "title-ocean-gradient",
		name: "Ocean",
		category: "titles",
		element: {
			content: "OCEAN",
			fontSize: 76,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "900",
			textCase: "uppercase",
			gradient: { enabled: true, colors: ["#06b6d4", "#8b5cf6"], angle: 90 },
			letterSpacing: 4,
		},
	},
	{
		id: "title-3d-shadow",
		name: "3D Shadow",
		category: "titles",
		element: {
			content: "DEPTH",
			fontSize: 80,
			fontFamily: "Impact",
			color: "#facc15",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 3 },
			shadow: { color: "#92400e", offsetX: 4, offsetY: 4, blur: 0 },
		},
	},
	{
		id: "title-minimal",
		name: "Minimal",
		category: "titles",
		element: {
			content: "minimal",
			fontSize: 60,
			fontFamily: "Inter",
			color: "#a1a1aa",
			fontWeight: "300",
			letterSpacing: 8,
		},
	},

	// ═══ SUBTITLES ═══
	{
		id: "subtitle-classic",
		name: "Classic",
		category: "subtitles",
		element: {
			content: "Subtitle text here",
			fontSize: 36,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "600",
			stroke: { color: "#000000", width: 2 },
			transform: { scale: 1, position: { x: 0, y: 200 }, rotate: 0 },
		},
	},
	{
		id: "subtitle-boxed",
		name: "Boxed",
		category: "subtitles",
		element: {
			content: "Boxed subtitle",
			fontSize: 32,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "500",
			backgroundColor: "rgba(0,0,0,0.75)",
			transform: { scale: 1, position: { x: 0, y: 200 }, rotate: 0 },
		},
	},
	{
		id: "subtitle-highlight",
		name: "Highlight",
		category: "subtitles",
		element: {
			content: "Highlighted",
			fontSize: 34,
			fontFamily: "Inter",
			color: "#000000",
			fontWeight: "700",
			backgroundColor: "#facc15",
			transform: { scale: 1, position: { x: 0, y: 200 }, rotate: 0 },
		},
	},
	{
		id: "subtitle-karaoke",
		name: "Karaoke",
		category: "subtitles",
		element: {
			content: "Sing along",
			fontSize: 40,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "800",
			stroke: { color: "#000000", width: 3 },
			gradient: { enabled: true, colors: ["#fbbf24", "#f59e0b"], angle: 0 },
			transform: { scale: 1, position: { x: 0, y: 180 }, rotate: 0 },
		},
	},

	// ═══ SOCIAL ═══
	{
		id: "social-tiktok",
		name: "TikTok POV",
		category: "social",
		element: {
			content: "POV:",
			fontSize: 56,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "900",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 3 },
			shadow: { color: "rgba(0,0,0,0.5)", offsetX: 2, offsetY: 2, blur: 4 },
		},
	},
	{
		id: "social-youtube-red",
		name: "YT Red",
		category: "social",
		element: {
			content: "SUBSCRIBE",
			fontSize: 52,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "900",
			textCase: "uppercase",
			bubbleStyle: "pill",
			bubbleColor: "#ff0000",
			bubblePadding: 18,
		},
	},
	{
		id: "social-ig-story",
		name: "IG Story",
		category: "social",
		element: {
			content: "Swipe Up",
			fontSize: 44,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "700",
			gradient: { enabled: true, colors: ["#f59e0b", "#ec4899"], angle: 45 },
			shadow: { color: "rgba(0,0,0,0.4)", offsetX: 0, offsetY: 2, blur: 8 },
		},
	},
	{
		id: "social-hashtag",
		name: "Hashtag",
		category: "social",
		element: {
			content: "#trending",
			fontSize: 48,
			fontFamily: "Inter",
			color: "#60a5fa",
			fontWeight: "700",
			fontStyle: "italic",
		},
	},
	{
		id: "social-meme-top",
		name: "Meme Top",
		category: "social",
		element: {
			content: "WHEN YOU",
			fontSize: 52,
			fontFamily: "Impact",
			color: "#ffffff",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 3 },
			transform: { scale: 1, position: { x: 0, y: -180 }, rotate: 0 },
		},
	},
	{
		id: "social-reaction",
		name: "Reaction",
		category: "social",
		element: {
			content: "NO WAY",
			fontSize: 64,
			fontFamily: "Impact",
			color: "#fbbf24",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 4 },
			shadow: { color: "rgba(0,0,0,0.7)", offsetX: 3, offsetY: 3, blur: 0 },
		},
	},

	// ═══ GAMING ═══
	{
		id: "gaming-fire",
		name: "Fire",
		category: "gaming",
		element: {
			content: "EPIC",
			fontSize: 80,
			fontFamily: "Impact",
			color: "#ff4500",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 4 },
			glow: { color: "#ff6600", intensity: 15 },
		},
	},
	{
		id: "gaming-glitch",
		name: "Glitch",
		category: "gaming",
		element: {
			content: "GLITCH",
			fontSize: 72,
			fontFamily: "Impact",
			color: "#00ff88",
			fontWeight: "bold",
			textCase: "uppercase",
			letterSpacing: 8,
			stroke: { color: "#ff0066", width: 2 },
			shadow: { color: "#00ff88", offsetX: -3, offsetY: 3, blur: 0 },
		},
	},
	{
		id: "gaming-victory",
		name: "Victory",
		category: "gaming",
		element: {
			content: "VICTORY",
			fontSize: 76,
			fontFamily: "Impact",
			color: "#fbbf24",
			fontWeight: "bold",
			textCase: "uppercase",
			gradient: { enabled: true, colors: ["#fbbf24", "#f59e0b"], angle: 180 },
			stroke: { color: "#78350f", width: 3 },
			glow: { color: "#f59e0b", intensity: 10 },
		},
	},
	{
		id: "gaming-eliminated",
		name: "Eliminated",
		category: "gaming",
		element: {
			content: "ELIMINATED",
			fontSize: 68,
			fontFamily: "Impact",
			color: "#ef4444",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#7f1d1d", width: 3 },
			letterSpacing: 4,
		},
	},
	{
		id: "gaming-combo",
		name: "Combo",
		category: "gaming",
		element: {
			content: "10x COMBO",
			fontSize: 64,
			fontFamily: "Impact",
			color: "#ffffff",
			fontWeight: "bold",
			textCase: "uppercase",
			gradient: { enabled: true, colors: ["#a855f7", "#ec4899"], angle: 90 },
			stroke: { color: "#000000", width: 3 },
			glow: { color: "#a855f7", intensity: 12 },
		},
	},
	{
		id: "gaming-gg",
		name: "GG",
		category: "gaming",
		element: {
			content: "GG",
			fontSize: 96,
			fontFamily: "Impact",
			color: "#22c55e",
			fontWeight: "bold",
			textCase: "uppercase",
			stroke: { color: "#000000", width: 5 },
			shadow: { color: "#166534", offsetX: 4, offsetY: 4, blur: 0 },
		},
	},

	// ═══ NEON ═══
	{
		id: "neon-blue",
		name: "Blue Neon",
		category: "neon",
		element: {
			content: "NEON",
			fontSize: 64,
			fontFamily: "Inter",
			color: "#60a5fa",
			fontWeight: "bold",
			textCase: "uppercase",
			glow: { color: "#3b82f6", intensity: 20 },
			letterSpacing: 6,
		},
	},
	{
		id: "neon-pink",
		name: "Hot Pink",
		category: "neon",
		element: {
			content: "GLOW",
			fontSize: 64,
			fontFamily: "Inter",
			color: "#f472b6",
			fontWeight: "bold",
			textCase: "uppercase",
			glow: { color: "#ec4899", intensity: 22 },
			letterSpacing: 6,
		},
	},
	{
		id: "neon-green",
		name: "Matrix",
		category: "neon",
		element: {
			content: "MATRIX",
			fontSize: 60,
			fontFamily: "Courier New",
			color: "#4ade80",
			fontWeight: "bold",
			textCase: "uppercase",
			glow: { color: "#22c55e", intensity: 18 },
			letterSpacing: 8,
		},
	},
	{
		id: "neon-purple",
		name: "Ultraviolet",
		category: "neon",
		element: {
			content: "ULTRA",
			fontSize: 64,
			fontFamily: "Inter",
			color: "#c084fc",
			fontWeight: "800",
			textCase: "uppercase",
			glow: { color: "#a855f7", intensity: 22 },
			letterSpacing: 6,
		},
	},
	{
		id: "neon-red",
		name: "Red Alert",
		category: "neon",
		element: {
			content: "ALERT",
			fontSize: 64,
			fontFamily: "Impact",
			color: "#f87171",
			fontWeight: "bold",
			textCase: "uppercase",
			glow: { color: "#ef4444", intensity: 20 },
			letterSpacing: 4,
		},
	},
	{
		id: "neon-sign",
		name: "Neon Sign",
		category: "neon",
		element: {
			content: "OPEN",
			fontSize: 56,
			fontFamily: "Inter",
			color: "#f472b6",
			fontWeight: "bold",
			textCase: "uppercase",
			bubbleStyle: "neon-box",
			bubbleColor: "#ec4899",
			bubblePadding: 20,
			glow: { color: "#ec4899", intensity: 14 },
		},
	},

	// ═══ BUBBLES ═══
	{
		id: "bubble-rounded-blue",
		name: "Blue Bubble",
		category: "bubbles",
		element: {
			content: "Hello!",
			fontSize: 40,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "600",
			bubbleStyle: "rounded",
			bubbleColor: "#3b82f6",
			bubblePadding: 20,
		},
	},
	{
		id: "bubble-pill-red",
		name: "Subscribe",
		category: "bubbles",
		element: {
			content: "Subscribe",
			fontSize: 36,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "bold",
			bubbleStyle: "pill",
			bubbleColor: "#ef4444",
			bubblePadding: 16,
		},
	},
	{
		id: "bubble-pill-gradient",
		name: "Gradient Pill",
		category: "bubbles",
		element: {
			content: "NEW",
			fontSize: 36,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "800",
			textCase: "uppercase",
			bubbleStyle: "pill",
			bubbleColor: "#8b5cf6",
			bubblePadding: 18,
			letterSpacing: 4,
		},
	},
	{
		id: "bubble-speech-white",
		name: "Speech",
		category: "bubbles",
		element: {
			content: "Hey there!",
			fontSize: 36,
			fontFamily: "Inter",
			color: "#000000",
			fontWeight: "500",
			bubbleStyle: "speech",
			bubbleColor: "#ffffff",
			bubblePadding: 20,
		},
	},
	{
		id: "bubble-speech-blue",
		name: "iMessage",
		category: "bubbles",
		element: {
			content: "Sent from iPhone",
			fontSize: 32,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "normal",
			bubbleStyle: "speech",
			bubbleColor: "#2563eb",
			bubblePadding: 18,
		},
	},
	{
		id: "bubble-thought",
		name: "Thought",
		category: "bubbles",
		element: {
			content: "Hmm...",
			fontSize: 36,
			fontFamily: "Inter",
			color: "#000000",
			fontWeight: "normal",
			fontStyle: "italic",
			bubbleStyle: "thought",
			bubbleColor: "#f0f0f0",
			bubblePadding: 22,
		},
	},
	{
		id: "bubble-label-breaking",
		name: "Breaking",
		category: "bubbles",
		element: {
			content: "BREAKING",
			fontSize: 42,
			fontFamily: "Inter",
			color: "#ffffff",
			fontWeight: "900",
			textCase: "uppercase",
			bubbleStyle: "label",
			bubbleColor: "#dc2626",
			bubblePadding: 16,
			letterSpacing: 3,
		},
	},
	{
		id: "bubble-glitch-error",
		name: "Error",
		category: "bubbles",
		element: {
			content: "ERROR 404",
			fontSize: 44,
			fontFamily: "Courier New",
			color: "#00ff00",
			fontWeight: "bold",
			textCase: "uppercase",
			bubbleStyle: "glitch",
			bubbleColor: "#111111",
			bubblePadding: 14,
			letterSpacing: 4,
		},
	},

	// ═══ HANDWRITTEN ═══
	{
		id: "handwritten-note",
		name: "Sticky Note",
		category: "handwritten",
		element: {
			content: "Remember this!",
			fontSize: 44,
			fontFamily: "Comic Sans MS",
			color: "#1a1a1a",
			fontWeight: "bold",
			backgroundColor: "#fbbf24",
		},
	},
	{
		id: "handwritten-chalk",
		name: "Chalk",
		category: "handwritten",
		element: {
			content: "Chalk Text",
			fontSize: 56,
			fontFamily: "Comic Sans MS",
			color: "#f5f5f4",
			fontWeight: "bold",
			shadow: { color: "rgba(255,255,255,0.3)", offsetX: 1, offsetY: 1, blur: 2 },
		},
	},
	{
		id: "handwritten-marker",
		name: "Marker",
		category: "handwritten",
		element: {
			content: "Important!",
			fontSize: 48,
			fontFamily: "Comic Sans MS",
			color: "#ef4444",
			fontWeight: "bold",
			fontStyle: "italic",
			textDecoration: "underline",
		},
	},
	{
		id: "handwritten-pencil",
		name: "Pencil",
		category: "handwritten",
		element: {
			content: "sketch notes",
			fontSize: 40,
			fontFamily: "Comic Sans MS",
			color: "#78716c",
			fontWeight: "normal",
			fontStyle: "italic",
		},
	},
];

export const BUILT_IN_FONTS = [
	{ family: "Inter", label: "Inter", category: "sans-serif" as const },
	{ family: "Arial", label: "Arial", category: "sans-serif" as const },
	{ family: "Helvetica", label: "Helvetica", category: "sans-serif" as const },
	{ family: "Roboto", label: "Roboto", category: "sans-serif" as const },
	{ family: "Roboto Condensed", label: "Roboto Condensed", category: "sans-serif" as const },
	{ family: "Montserrat", label: "Montserrat", category: "sans-serif" as const },
	{ family: "Bebas Neue", label: "Bebas Neue", category: "display" as const },
	{ family: "Georgia", label: "Georgia", category: "serif" as const },
	{ family: "Times New Roman", label: "Times New Roman", category: "serif" as const },
	{ family: "Courier New", label: "Courier New", category: "monospace" as const },
	{ family: "Verdana", label: "Verdana", category: "sans-serif" as const },
	{ family: "Impact", label: "Impact", category: "display" as const },
	{ family: "Comic Sans MS", label: "Comic Sans MS", category: "handwriting" as const },
] as const;

export type FontCategory = "sans-serif" | "serif" | "monospace" | "display" | "handwriting" | "custom";
