import type { TransitionPreset, TransitionCategory } from "../types/transitions";
import type { TransitionType } from "../types/transitions";

type TransitionPresetInput = Omit<
	TransitionPreset,
	"previewRenderer" | "exportSupported" | "modernRank"
> & {
	previewRenderer?: TransitionType;
	exportSupported?: boolean;
	modernRank?: number;
};

function defineTransitionPresets(presets: TransitionPresetInput[]): TransitionPreset[] {
	return presets.map((preset, index) => ({
		...preset,
		previewRenderer: preset.previewRenderer ?? preset.type,
		exportSupported: preset.exportSupported ?? true,
		modernRank: preset.modernRank ?? (preset.category === "modern" ? index - 1000 : index),
	}));
}

export const TRANSITION_CATEGORIES: { key: TransitionCategory; label: string }[] = [
	{ key: "fade", label: "Fade" },
	{ key: "slide", label: "Slide" },
	{ key: "wipe", label: "Wipe" },
	{ key: "zoom", label: "Zoom" },
	{ key: "push", label: "Push" },
	{ key: "cover", label: "Cover & reveal" },
	{ key: "modern", label: "Smooth & motion" },
	{ key: "shape", label: "Iris & shapes" },
];

export const TRANSITION_PRESETS: TransitionPreset[] = defineTransitionPresets([
	// ── Fade ──
	{
		type: "crossfade",
		label: "Crossfade",
		description: "Opacity blend (xfade fade)",
		category: "fade",
		defaultDuration: 0.5,
		ffmpegName: "fade",
	},
	{
		type: "fadeToBlack",
		label: "Fade to Black",
		description: "Through black (xfade fadeblack)",
		category: "fade",
		defaultDuration: 0.5,
		ffmpegName: "fadeblack",
	},
	{
		type: "fadeToWhite",
		label: "Fade to White",
		description: "Through white (xfade fadewhite)",
		category: "fade",
		defaultDuration: 0.5,
		ffmpegName: "fadewhite",
	},
	{
		type: "dissolve",
		label: "Dissolve",
		description: "Pixel dissolve (xfade dissolve)",
		category: "fade",
		defaultDuration: 0.5,
		ffmpegName: "dissolve",
	},
	{
		type: "fadegrays",
		label: "Fade Grays",
		description: "Neutralize then cross (xfade fadegrays)",
		category: "fade",
		defaultDuration: 0.55,
		ffmpegName: "fadegrays",
	},
	{
		type: "fadefast",
		label: "Fast Fade",
		description: "Short punchy blend (xfade fadefast)",
		category: "fade",
		defaultDuration: 0.22,
		ffmpegName: "fadefast",
	},
	{
		type: "fadeslow",
		label: "Slow Fade",
		description: "Long smooth blend (xfade fadeslow)",
		category: "fade",
		defaultDuration: 0.9,
		ffmpegName: "fadeslow",
	},

	// ── Slide ──
	{
		type: "slideLeft",
		label: "Slide Left",
		description: "Incoming from the right (xfade slideleft)",
		category: "slide",
		defaultDuration: 0.4,
		ffmpegName: "slideleft",
	},
	{
		type: "slideRight",
		label: "Slide Right",
		description: "Incoming from the left (xfade slideright)",
		category: "slide",
		defaultDuration: 0.4,
		ffmpegName: "slideright",
	},
	{
		type: "slideUp",
		label: "Slide Up",
		description: "Incoming from below (xfade slideup)",
		category: "slide",
		defaultDuration: 0.4,
		ffmpegName: "slideup",
	},
	{
		type: "slideDown",
		label: "Slide Down",
		description: "Incoming from above (xfade slidedown)",
		category: "slide",
		defaultDuration: 0.4,
		ffmpegName: "slidedown",
	},

	// ── Wipe ──
	{
		type: "wipeLeft",
		label: "Wipe Left",
		description: "Edge moves left (xfade wipeleft)",
		category: "wipe",
		defaultDuration: 0.4,
		ffmpegName: "wipeleft",
	},
	{
		type: "wipeRight",
		label: "Wipe Right",
		description: "Edge moves right (xfade wiperight)",
		category: "wipe",
		defaultDuration: 0.4,
		ffmpegName: "wiperight",
	},
	{
		type: "wipeUp",
		label: "Wipe Up",
		description: "Edge moves up (xfade wipeup)",
		category: "wipe",
		defaultDuration: 0.4,
		ffmpegName: "wipeup",
	},
	{
		type: "wipeDown",
		label: "Wipe Down",
		description: "Edge moves down (xfade wipedown)",
		category: "wipe",
		defaultDuration: 0.4,
		ffmpegName: "wipedown",
	},

	// ── Zoom ──
	{
		type: "zoomIn",
		label: "Zoom In",
		description: "xfade zoomin (only built-in zoom transition)",
		category: "zoom",
		defaultDuration: 0.5,
		ffmpegName: "zoomin",
	},

	// ── Shape / iris (xfade names) ──
	{
		type: "circleWipe",
		label: "Circle Open",
		description: "Iris opens from center (xfade circleopen)",
		category: "shape",
		defaultDuration: 0.5,
		ffmpegName: "circleopen",
	},
	{
		type: "circleClose",
		label: "Circle Close",
		description: "Iris closes to center (xfade circleclose)",
		category: "shape",
		defaultDuration: 0.5,
		ffmpegName: "circleclose",
	},
	{
		type: "diamondWipe",
		label: "Diamond Wipe",
		description: "Diamond iris (custom xfade expr, export parity)",
		category: "shape",
		defaultDuration: 0.5,
		ffmpegName: "custom",
	},
	{
		type: "clockWipe",
		label: "Radial Wipe",
		description: "Clock-style radial (xfade radial)",
		category: "shape",
		defaultDuration: 0.55,
		ffmpegName: "radial",
	},
	{
		type: "horzOpen",
		label: "Horizontal Open",
		description: "xfade horzopen",
		category: "shape",
		defaultDuration: 0.45,
		ffmpegName: "horzopen",
	},
	{
		type: "horzClose",
		label: "Horizontal Close",
		description: "xfade horzclose",
		category: "shape",
		defaultDuration: 0.45,
		ffmpegName: "horzclose",
	},
	{
		type: "vertOpen",
		label: "Vertical Open",
		description: "xfade vertopen",
		category: "shape",
		defaultDuration: 0.45,
		ffmpegName: "vertopen",
	},
	{
		type: "vertClose",
		label: "Vertical Close",
		description: "xfade vertclose",
		category: "shape",
		defaultDuration: 0.45,
		ffmpegName: "vertclose",
	},

	// ── Push ──
	{
		type: "pushLeft",
		label: "Push Left",
		description: "xfade slideleft (same geometry as push)",
		category: "push",
		defaultDuration: 0.4,
		ffmpegName: "slideleft",
	},
	{
		type: "pushRight",
		label: "Push Right",
		description: "xfade slideright",
		category: "push",
		defaultDuration: 0.4,
		ffmpegName: "slideright",
	},
	{
		type: "pushUp",
		label: "Push Up",
		description: "xfade slideup",
		category: "push",
		defaultDuration: 0.4,
		ffmpegName: "slideup",
	},
	{
		type: "pushDown",
		label: "Push Down",
		description: "xfade slidedown",
		category: "push",
		defaultDuration: 0.4,
		ffmpegName: "slidedown",
	},

	// ── Cover & reveal (xfade slide family — valid names only) ──
	{
		type: "coverLeft",
		label: "Cover Left",
		description: "Incoming from right (xfade slideright)",
		category: "cover",
		defaultDuration: 0.4,
		ffmpegName: "slideright",
	},
	{
		type: "coverRight",
		label: "Cover Right",
		description: "Incoming from left (xfade slideleft)",
		category: "cover",
		defaultDuration: 0.4,
		ffmpegName: "slideleft",
	},
	{
		type: "revealLeft",
		label: "Reveal Left",
		description: "Outgoing exits left (xfade slideleft)",
		category: "cover",
		defaultDuration: 0.4,
		ffmpegName: "slideleft",
	},
	{
		type: "revealRight",
		label: "Reveal Right",
		description: "Outgoing exits right (xfade slideright)",
		category: "cover",
		defaultDuration: 0.4,
		ffmpegName: "slideright",
	},

	// ── Premium procedural mattes (custom xfade; same math in canvas preview) ──
	{
		type: "prismSweep",
		label: "Prism Sweep",
		description: "Angled soft sweep with a bright specular band (custom xfade)",
		category: "modern",
		defaultDuration: 0.55,
		ffmpegName: "custom",
		modernRank: -1000,
	},
	{
		type: "glitchBlocks",
		label: "Glitch Blocks",
		description: "Staggered horizontal block reveal (custom xfade)",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "custom",
		modernRank: -999,
	},
	{
		type: "shutterFlash",
		label: "Shutter Flash",
		description: "Alternating vertical shutters with a flash accent (custom xfade)",
		category: "modern",
		defaultDuration: 0.4,
		ffmpegName: "custom",
		modernRank: -998,
	},
	{
		type: "inkBloom",
		label: "Ink Bloom",
		description: "Organic center bloom with procedural edge turbulence (custom xfade)",
		category: "modern",
		defaultDuration: 0.65,
		ffmpegName: "custom",
		modernRank: -997,
	},
	{
		type: "diagTl",
		label: "Diagonal TL",
		description: "xfade diagtl",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "diagtl",
	},
	{
		type: "diagTr",
		label: "Diagonal TR",
		description: "xfade diagtr",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "diagtr",
	},
	{
		type: "diagBl",
		label: "Diagonal BL",
		description: "xfade diagbl",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "diagbl",
	},
	{
		type: "diagBr",
		label: "Diagonal BR",
		description: "xfade diagbr",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "diagbr",
	},
	{
		type: "wipeTl",
		label: "Corner Wipe TL",
		description: "xfade wipetl",
		category: "modern",
		defaultDuration: 0.4,
		ffmpegName: "wipetl",
	},
	{
		type: "wipeTr",
		label: "Corner Wipe TR",
		description: "xfade wipetr",
		category: "modern",
		defaultDuration: 0.4,
		ffmpegName: "wipetr",
	},
	{
		type: "wipeBl",
		label: "Corner Wipe BL",
		description: "xfade wipebl",
		category: "modern",
		defaultDuration: 0.4,
		ffmpegName: "wipebl",
	},
	{
		type: "wipeBr",
		label: "Corner Wipe BR",
		description: "xfade wipebr",
		category: "modern",
		defaultDuration: 0.4,
		ffmpegName: "wipebr",
	},
	{
		type: "squeezeH",
		label: "Squeeze Horizontal",
		description: "xfade squeezeh",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "squeezeh",
	},
	{
		type: "squeezeV",
		label: "Squeeze Vertical",
		description: "xfade squeezev",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "squeezev",
	},
	{
		type: "hlSlice",
		label: "Slice HL",
		description: "xfade hlslice",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "hlslice",
	},
	{
		type: "hrSlice",
		label: "Slice HR",
		description: "xfade hrslice",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "hrslice",
	},
	{
		type: "vuSlice",
		label: "Slice VU",
		description: "xfade vuslice",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "vuslice",
	},
	{
		type: "vdSlice",
		label: "Slice VD",
		description: "xfade vdslice",
		category: "modern",
		defaultDuration: 0.45,
		ffmpegName: "vdslice",
	},
	{
		type: "hblurTransition",
		label: "Blur Dissolve",
		description: "xfade hblur (horizontal blur blend)",
		category: "modern",
		defaultDuration: 0.55,
		ffmpegName: "hblur",
	},
]);

export function getTransitionPreset(type: string): TransitionPreset | undefined {
	return TRANSITION_PRESETS.find((p) => p.type === type);
}
